const fs = require('fs');

let text = fs.readFileSync('App.js', 'utf8');

// Replace any sequence of broken UTF-8 characters
const replacements = [
  [/ðŸ ”/g, '🍔'],
  [/ðŸŒ­/g, '🌭'],
  [/ðŸŒ¯/g, '🌯'],
  [/ðŸ Ÿ/g, '🍟'],
  [/ðŸŒ½/g, '🌽'],
  [/ðŸ¥¤/g, '🥤'],
  [/ðŸ ‹/g, '🍋'],
  [/ðŸ º/g, '🍺'],
  [/ðŸ›’/g, '🛒'],
  [/â ³/g, '⏳'],
  [/ðŸ”¥/g, '🔥'],
  [/âœ ï¸ /g, '✏️'],
  [/ðŸŸ¢/g, '🟢'],
  [/âšï¸ /g, '⚠️'],
  [/âš ï¸ /g, '⚠️'],
  [/ðŸ–¨ï¸ /g, '🖨️'],
  [/ðŸ“ /g, '📌'],
  [/ðŸ ½ï¸ /g, '🍽️'],
  [/âš™ï¸ /g, '⚙️'],
  [/â Œ/g, '❌'],
  [/ðŸ” /g, '🔍'],
  [/ðŸŽµ/g, '🎵'],
  [/ðŸ“¡/g, '📡'],
  [/ðŸ””/g, '🔔'],
  [/ðŸ›Žï¸ /g, '🛎️'],
  [/ðŸš€/g, '🚀'],
  [/ðŸ’µ/g, '💵'],
  [/ðŸ“²/g, '📱'],
  [/ðŸ‘¥/g, '👥'],
  [/ðŸ”’/g, '🔒'],
  [/ðŸŽ‰/g, '🎉'],
  [/âœ…/g, '✅'],
  [/ðŸ“¦/g, '📦'],
  [/ðŸ‘¤/g, '👤'],
  [/ðŸ“‹/g, '📋'],
  [/ðŸ§¾/g, '🧾'],
  [/âœ¨/g, '✨'],
  [/âž•/g, '➕'],
  [/ðŸ“¸/g, '📸'],
  [/ðŸ“Š/g, '📊'],
  [/ðŸ’¸/g, '💸'],
  [/ðŸ ·ï¸ /g, '🍷'],
  [/ðŸ“…/g, '📅'],
  [/âž–/g, '➖'],
  [/ðŸ•’/g, '🕒'],
  [/ðŸ’³/g, '💳'],
  [/ðŸ”‘/g, '🔑'],
  [/ðŸ’°/g, '💰'],
  [/ðŸ ¦/g, '🍦'],
  [/â˜•/g, '☕'],
  [/âš ️/g, '⚠️'],
  [/âš️/g, '⚠️'],
  [/â†’/g, '→'],
  [/ðŸ‘¨â€\\x8DðŸ ³/g, '👨‍🍳'],
  [/ðŸ‘¨â€ ðŸ ³/g, '👨‍🍳'],
  [/âœ ️/g, '✏️'],
  [/âˆ’/g, '−'],
  [/🍔¥/g, '🍔'],
  [/âœ“/g, '✓'],
  [/â”€â”€â”€/g, '---'],
  [/â”€â”€/g, '--'],
  [/â”€/g, '-'],
  [/ââ€ â‚¬ââ€ â‚¬ââ€ â‚¬/g, '---'],
  [/Â¿/g, '¿'],
  [/â€¢/g, '•'],
  [/â€”/g, '—'],
  [/Ã—/g, '×'],
  [/â¬…/g, '⬅'],
  [/RÃ PIDA/g, 'RÁPIDA'],
  [/Ã /g, 'Á'],
  [/Ã‰/g, 'É'],
  [/Ã\x8D/g, 'Í'],
  [/Ã“/g, 'Ó'],
  [/Ãš/g, 'Ú'],
  [/Ã‘/g, 'Ñ'],
  [/Ã¡/g, 'á'],
  [/Ã©/g, 'é'],
  [/Ã\xAD/g, 'í'],
  [/Ã­/g, 'í'],
  [/Ã³/g, 'ó'],
  [/Ãº/g, 'ú'],
  [/Ã±/g, 'ñ'],
  [/GestiÃ³n/g, 'Gestión'],
  [/MenÃº/g, 'Menú'],
  [/CategorÃ\xADa/g, 'Categoría'],
  [/DescripciÃ³n/g, 'Descripción'],
  [/Ãšltimos/g, 'Últimos'],
  [/estÃ¡/g, 'está'],
  [/registrarÃ¡/g, 'registrará'],
  [/sesiÃ³n/g, 'sesión'],
  [/fÃ\xADsica/g, 'física'],
  [/ObservaciÃ³n/g, 'Observación'],
  [/CancelaciÃ³n/g, 'Cancelación'],
  [/aÃºn/g, 'aún'],
  [/AUDITORÃ A/g, 'AUDITORÍA'],
  [/AcciÃ³n/g, 'Acción'],
  [/MÃ¡x\./g, 'Máx.'],
  [/ConfiguraciÃ³n/g, 'Configuración'],
  [/ImpresiÃ³n/g, 'Impresión'],
  [/DirecciÃ³n/g, 'Dirección'],
  [/MÃ©todo/g, 'Método'],
  [/ArtÃ\xADculos/g, 'Artículos'],
  [/PÃ©rez/g, 'Pérez'],
  [/dÃ\xADgitos/g, 'dígitos'],
  [/NÃ³mina/g, 'Nómina'],
  [/invÃ¡lido/g, 'inválido'],
  [/SESIÃ“N/g, 'SESIÓN'],
  [/NOTIFICACIÃ“N/g, 'NOTIFICACIÓN'],
  [/ACUMULACIÃ“N/g, 'ACUMULACIÓN'],
  [/CORRECCIÃ“N/g, 'CORRECCIÓN'],
  [/Ã“RDENES/g, 'ÓRDENES'],
  [/SELECCIÃ“N/g, 'SELECCIÓN'],
  [/HISTÃ“RICOS/g, 'HISTÓRICOS'],
  [/LIQUIDACIÃ“N/g, 'LIQUIDACIÓN'],
  [/ACTUALIZACIÃ“N/g, 'ACTUALIZACIÓN'],
  [/Ã‰xito/g, 'Éxito'],
  [/Ã©xito/g, 'éxito'],
  [/ðŸ¥›/g, '🥛'],
  [/ðŸ ¹/g, '🍹'],
  [/Â¡/g, '¡'],
  [/Ã /g, 'í'],
];

for (const [bad, good] of replacements) {
  text = text.replace(bad, good);
}

fs.writeFileSync('App.js', text, 'utf8');
console.log('Final regex sweep applied');
